export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const SET_COLOR = "SET_COLOR";
export const MAININCREMENT = "MAININCREMENT";
export const MAINDECREMENT = "MAINDECREMENT";
